/* Simulation code for simpleCircuitEqns generated by the OpenModelica Compiler OpenModelica v1.20.0-dev-10-gd29d3275d8 (64-bit). */
#if !defined(simpleCircuitEqns__MODEL_H)
#define simpleCircuitEqns__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "simpleCircuitEqns_functions.h"


extern void simpleCircuitEqns_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void simpleCircuitEqns_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int simpleCircuitEqns_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int simpleCircuitEqns_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int simpleCircuitEqns_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int simpleCircuitEqns_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int simpleCircuitEqns_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int simpleCircuitEqns_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int simpleCircuitEqns_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int simpleCircuitEqns_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int simpleCircuitEqns_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int simpleCircuitEqns_checkForAsserts(DATA *data, threadData_t *threadData);
extern int simpleCircuitEqns_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int simpleCircuitEqns_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int simpleCircuitEqns_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* simpleCircuitEqns_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* simpleCircuitEqns_relationDescription(int i);
extern void simpleCircuitEqns_function_initSample(DATA *data, threadData_t *threadData);
extern int simpleCircuitEqns_initialAnalyticJacobianG(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int simpleCircuitEqns_initialAnalyticJacobianA(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int simpleCircuitEqns_initialAnalyticJacobianB(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int simpleCircuitEqns_initialAnalyticJacobianC(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int simpleCircuitEqns_initialAnalyticJacobianD(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int simpleCircuitEqns_initialAnalyticJacobianF(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int simpleCircuitEqns_functionJacG_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int simpleCircuitEqns_functionJacA_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int simpleCircuitEqns_functionJacB_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int simpleCircuitEqns_functionJacC_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int simpleCircuitEqns_functionJacD_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int simpleCircuitEqns_functionJacF_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* simpleCircuitEqns_linear_model_frame(void);
extern const char* simpleCircuitEqns_linear_model_datarecovery_frame(void);
extern int simpleCircuitEqns_mayer(DATA* data, modelica_real** res, short *);
extern int simpleCircuitEqns_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int simpleCircuitEqns_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int simpleCircuitEqns_setInputData(DATA *data, const modelica_boolean file);
extern int simpleCircuitEqns_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void simpleCircuitEqns_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void simpleCircuitEqns_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int simpleCircuitEqns_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void simpleCircuitEqns_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void simpleCircuitEqns_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int simpleCircuitEqns_inputNames(DATA* data, char ** names);
extern int simpleCircuitEqns_dataReconciliationInputNames(DATA* data, char ** names);
extern int simpleCircuitEqns_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int simpleCircuitEqns_functionLocalKnownVars(DATA*, threadData_t*);
extern int simpleCircuitEqns_symbolicInlineSystem(DATA*, threadData_t*);

#include "simpleCircuitEqns_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(simpleCircuitEqns__MODEL_H) */


