/* Additional record code for simpleCircuitEqns generated by the OpenModelica Compiler OpenModelica v1.20.0-dev-10-gd29d3275d8 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "simpleCircuitEqns_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

